products = [
  {
    id: 1,
    name: "T-shirt",
    category: "Fashion",
    price: 100,
    quntity: 1,
    image: "./Images/product1.jpg",
    size: "large",
  },
  {
    id: 2,
    name: "Airbods",
    category: "Phone Accessories",
    price: 120,
    quntity: 1,
    image: "./Images/product2.jpg",
    size: "large",
  },
  {
    id: 3,
    name: "Cap",
    category: "Men Accessories",
    price: 50,
    quntity: 1,
    image: "./Images/product6.jpg",
    size: "medium",
  },
  {
    id: 4,
    name: "Jacket",
    category: "Fashion",
    price: 50,
    quntity: 1,
    image: "./Images/product3.jpg",
    size: "large",
  },
  {
    id: 5,
    name: "Adidas Bottle",
    category: "Sport",
    price: 50,
    quntity: 1,
    image: "./Images/product4.jpg",
    size: "small",
  },
  {
    id: 6,
    name: "Glasses",
    category: "Men Accessories",
    price: 50,
    quntity: 1,
    image: "./Images/product5.jpg",
    size: "small",
  },
  {
    id: 7,
    name: "Bag Adidas",
    category: "Bags",
    price: 50,
    quntity: 1,
    image: "./Images/product7.jpg",
    size: "medium",
  },
  {
    id: 8,
    name: "Shoes Adidas",
    category: "Sport",
    price: 50,
    quntity: 1,
    image: "./Images/product8.jpg",
    size: "large",
  },
  {
    id: 9,
    name: "Bag",
    category: "Bags",
    price: 50,
    quntity: 1,
    image: "./Images/product9.png",
    size: "medium",
  },
];

localStorage.setItem("products", JSON.stringify(products));

// let products = [
//   {
//     id: 1,
//     name: "T-shirt",
//     category: "Fashion",
//     price: "100$",
//     quntity: "0",
//     image: "../Images/product1.jpg",
//   },
//   {
//     id: 2,
//     name: "Airbods",
//     category: "Phone Accessories",
//     price: "120$",
//     quntity: "0",
//     image: "../Images/product2.jpg",
//   },
//   {
//     id: 3,
//     name: "Cap",
//     category: "Men Accessories",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product6.jpg",
//   },
//   {
//     id: 4,
//     name: "Jacket",
//     category: "Fashion",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product3.jpg",
//   },
//   {
//     id: 5,
//     name: "Adidas Bottle",
//     category: "Sport",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product4.jpg",
//   },
//   {
//     id: 6,
//     name: "Glasses",
//     category: "Men Accessories",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product5.jpg",
//   },
//   {
//     id: 7,
//     name: "Bag Adidas",
//     category: "Bags",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product7.jpg",
//   },
//   {
//     id: 8,
//     name: "Shoes Adidas",
//     category: "Sport",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product8.jpg",
//   },
//   {
//     id: 9,
//     name: "Bag",
//     category: "Bags",
//     price: "50$",
//     quntity: "0",
//     image: "../Images/product9.png",
//   },
// ];

// localStorage.setItem("products", JSON.stringify(products));
